# @format

name: Sync Repos

on:
  push:
    branches:
      - main
  # You can add more triggers, such as scheduled events
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Push to tfenv repository
        run: |
          git config --global user.email "soniyaraibagi@gmail.com"
          git config --global user.name "soniyaraibagi"
          git clone https://${{ env.ORG_NAME }}:${{ secrets.PAT }}@github.com/${{ env.ORG_NAME }}/tfenv.git
          cd tfenv
          git remote add source https://${{ env.ORG_NAME }}:${{ secrets.PAT }}@github.com/${{ env.ORG_NAME }}/github-action.git
          git remote update
          git merge source/main --allow-unrelated-histories -m "Sync from github-action repository"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          ORG_NAME: sr-temp01
