name: Lint

on:
  push:
    branches-ignore:
      - main

jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Terraform lint file
        run: |
          echo "This is a Terraform lint file" > tflint

      - name: Terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: .